### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by clyquan** [MinimalCompact/thumbor#28]
Maybe I missed something,  and there are 404 errors like this:
### thumbor_stack_nginx-proxy.1.volqnjkijlcs@mg1    | nginx.1    | 2019/06/04 13:13:26 [error] 38#38: *43 open() "/usr/share/nginx/html/1Rm6SK3Eg8_RMcBqf5coRrFAbi0=/28e98d7f8f6727c010152821085cf4c7cd794c4.jpg" failed (2: No such file or directory), client: 10.255.0.2, server: localhost, request: "GET /1Rm6SK3Eg8_RMcBqf5coRrFAbi0=/28e98d7f8f6727c010152821085cf4c7cd794c4.jpg HTTP/1.1", host: "xxx.xxx.cn"

And I use minio as S3 storage for this.

**Comment by gingerlime** [comment]
How are you setting up your nginx-proxy and thumbor together? you can see some example [docker-compose recipes](https://github.com/MinimalCompact/thumbor/tree/master/recipes/docker-compose) with comments on how to mix the components together (pay attention in particular to volume mapping and `VIRTUAL_HOST` environment variable)

If you're still having trouble then please provide your full setup with as much details as possible

**Comment by clyquan** [comment]
The details list below:

```yaml
version: '3'
services:
  thumbor:
    image: minimalcompact/thumbor
    ports:
      - "8889:8000"
    environment:
      # VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
      # but you usually need to point it to your domain, e.g. thumbor.example.com
      - VIRTUAL_HOST=xx.xxx.cn
      # THUMBOR_NUM_PROCESSES control how many processes run inside the container
      # Normally this is set in connection with the number of CPU cores
      # Note however that you can also use the docker-compose scale option to dynamically
      # scale your thumbor instances
      - THUMBOR_NUM_PROCESSES=4
      # important security settings
      - SECURITY_KEY=**** # ...
      - ALLOW_UNSAFE_URL=False
      # this would allow CORS from any origin (you can restrict to specific origins if you want)
      - CORS_ALLOW_ORIGIN=*
      - AWS_ACCESS_KEY_ID=******
      - AWS_SECRET_ACCESS_KEY=****
      # for buckets with new signing algorithm (v4)
      # - S3_USE_SIGV4=true
      # - TC_AWS_REGION=eu-central-1
      - TC_AWS_ENDPOINT=***
      - TC_AWS_LOADER_BUCKET=xxx # your S3 bucket
      - LOADER=tc_aws.loaders.s3_loader
      # - LOG_LEVEL=debug
      - DETECTORS=['thumbor.detectors.queued_detector.queued_complete_detector']
      - STORAGE=thumbor.storages.mixed_storage
      - MIXED_STORAGE_FILE_STORAGE=thumbor.storages.file_storage
      - MIXED_STORAGE_DETECTOR_STORAGE=tc_redis.storages.redis_storage
      - RESULT_STORAGE=thumbor.result_storages.file_storage
      # Cache storage settings
      #
      # storage keeps the original image files cached
      - STORAGE_EXPIRATION_SECONDS=604800 # 1 week
      # result storage keeps the image version files cached
      - RESULT_STORAGE_EXPIRATION_SECONDS=14400 # 4 hours
      - REDIS_STORAGE_SERVER_HOST=192.168.0.206
      - REDIS_STORAGE_SERVER_PORT=6379
      - REDIS_STORAGE_SERVER_DB=0
      - REDIS_QUEUE_SERVER_HOST=192.168.0.206
      - REDIS_QUEUE_SERVER_PORT=6379
      - REDIS_QUEUE_SERVER_DB=0
      - MAX_WIDTH=1200
      - MAX_HEIGHT=800
      - UPLOAD_ENABLED=False
      - UPLOAD_DELETE_ALLOWED=False
      - UPLOAD_PUT_ALLOWED=False
      - UPLOAD_MAX_SIZE=0
      - QUALITY=90
      - MAX_AGE=86400
    volumes:
      - data:/data
      - logs:/logs
    deploy:
      # Note this would create 3 instances, each with THUMBOR_NUM_PROCESSES
      # (for docker-compose, this is ignored, but can be controlled using
      #  docker-compose up -d --scale thumbor=3)
      replicas: 1
      placement:
        constraints: [node.role     ==   manager]
    extra_hosts:
      - "xxx.xxx.cn:192.168.0.205"
    networks:
      - frontend
      
  nginx-proxy:
    image: minimalcompact/thumbor-nginx-proxy
    environment:
      # setting the DEFAULT_HOST to the same as the VIRTUAL_HOST above.
      # Makes sure it works irrespective of the host name
      # Normally this won't be necessary, but it helps for testing.
      - DEFAULT_HOST=xx.xxx.cn
    volumes:
      # this is essential for nginx-proxy to detect docker containers, scaling etc
      # see https://github.com/jwilder/nginx-proxy
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # mapping the same data folder, to allow nginx-proxy to fetch images from cache
      - data:/data
    ports:
      - "8888:80" # nginx cache port (with failover to thumbor)
    deploy:
      replicas: 1
      placement:
        constraints: [node.role     ==   manager]
    networks:
      - frontend

  remotecv:
    image: minimalcompact/remotecv
    environment:
      - REMOTECV_REDIS_HOST=192.168.0.206
      - REMOTECV_REDIS_PORT=6379
      - REMOTECV_REDIS_DATABASE=0
      - LOADER=remotecv_aws.loader
      - AWS_ACCESS_KEY_ID=**** # your AWS_ACCESS_KEY here
      - AWS_SECRET_ACCESS_KEY=**** # your AWS_SECRET_ACCESS_KEY here
      - AWS_LOADER_BUCKET=*** # your S3 bucket
    deploy:
      replicas: 1
    networks:
      - backend
volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  frontend:
  backend:

```
