### ISSUE TITLE
Thumbor don't find local images when using file loader and bind mount

### ISSUE THREAD

**Issue by IlCallo** [MinimalCompact/thumbor#82]
Hello there! Thank you for creating and maintaining this docker image.
I'm working on a [webpack loader](https://github.com/dreamonkey/responsive-image-loader) which uses thumbor to solve the Art Direction problem in websites development.

The loader works fine on linux environments with a local thumbor installation, but I'm trying to add Windows and Mac support and docker seems our best shot to unify the DX. Right now, we are testing the Windows integration.

Unluckily, it seems that using the file loader to work with images into a folder mounted via `--mount` option isn't working.
Right now I'm manually testing the system before automatizing the process and all I can get are 404 errors.

This is the command I use to launch the container
`docker run -p 8888:80 --name ril-thumbor --env-file .thumbor-env --mount type=bind,source="$(pwd)",target=/app/loader,readonly --rm minimalcompact/thumbor`

_.thumbor-env_
```
LOADER=thumbor.loaders.file_loader
RESULT_STORAGE_EXPIRATION_SECONDS=86400
STORES_CRYPTO_KEY_FOR_EACH_IMAGE=True
LOG_LEVEL=debug
DETECTORS=['thumbor.detectors.face_detector','thumbor.detectors.profile_detector','thumbor.detectors.feature_detector']
```

I use `docker exec -it ril-thumbor bash` to enter the container and check what's going on inside.

## What works

- The container starts correctly and thumbor starts listening and answering the requests when I hit `localhost:8888`
- Thumbor configuration, as found into `/app/thumbor.conf`, seems correct, all options provided via env file are correctly overriden
- The current directory is correctly mounted into `/app/loader` (which is the default `FILE_LOADER_ROOT_PATH`) and I can access and read the content of the mounted folder when connected via bash
- If I use a different loader, eg the default http loader, thumbor works as expected

## What doesn't work

Any request result in a 404 error, which leads me to think something is wrong with the path (the root path, the one we provide, or both).
We already successfully use thumbor in this way when it's installed locally, the only difference being `FILE_LOADER_ROOT_PATH` set to `/home/` (absolute paths to images are provided except the initial `/home/` part).

What URLs I tried, by accessing them via Chrome browser:
- `http://localhost:8888/unsafe/500x150/smart/src/assets/images/my-image.jpg`: this should be the correct one, AFAIK
- `http://localhost:8888/unsafe/500x150/smart/my-image.jpg`: we moved the image into `/app/loader` to check if the problem was about the path slashes, still 404, seems that's not the problem
- `http://localhost:8888/unsafe/500x150/smart/app/loader/src/assets/images/my-image.jpg`: random guess
- `http://localhost:8888/unsafe/500x150/smart/loader/src/assets/images/my-image.jpg`: random guess
- `http://localhost:8888/unsafe/500x150/src/assets/images/my-image.jpg`: random guess
- `http://localhost:8888/unsafe/500x150//src/assets/images/my-image.jpg`: strange random guess

Thumbor isn't providing any useful info even with debug log level, especially I cannot find a way to make thumbor tell me where it's actually searching the image, so I'm just going on blindly.

_Thumbor log with DEBUG level_
```
2020-08-04 07:02:45 thumbor:DEBUG METRICS: inc: response.count:1
2020-08-04 07:02:45 thumbor:DEBUG METRICS: inc: storage.miss:1
2020-08-04 07:02:45 tornado.access:WARNING 404 GET /unsafe/500x150/smart/src/assets/images/my-image.jpg (172.17.0.1) 3.21ms
2020-08-04 07:02:45 thumbor:DEBUG METRICS: timing: response.time:2
2020-08-04 07:02:45 thumbor:DEBUG METRICS: timing: response.time.404:2
2020-08-04 07:02:45 thumbor:DEBUG METRICS: inc: response.status.404:1
```

Other possible causes:
- there is some obscure option of thumbor configuration which is set by default on the docker image which isn't set into a normal thumbor installation
- the bind mount from a Windows host cause some esoteric path conflicts which I'm not aware of (even if I thought Docker main job was to avoid these problems)

Does this ring any bell to you? Have you run into something like this in the past?

**Comment by malmi** [comment]
I used volumes instead of a mount and it worked fine for me. Maybe this would be something to try? I never worked with mounts.

**Comment by IlCallo** [comment]
Could be a good thing to try, even if docs say `--mount` is the preferred way and I thought `type=bind` was more fitting in this case, due to the transitory nature of the container

**Comment by gingerlime** [comment]
Thanks for the detailed report @IlCallo. I'm also using volumes usually rather than mount, but I'm not sure if it makes a difference to be honest.

One thing worth checking is `FILE_STORAGE_ROOT_PATH` which you should probably set explicitly?

Here's a simple docker-compose example that works for me mapping a local `./images` folder

```yaml
version: '3'
services:
  thumbor:
    image: minimalcompact/thumbor
    environment:
      # VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
      # but you usually need to point it to your domain, e.g. thumbor.example.com
      - VIRTUAL_HOST=localhost
      # THUMBOR_NUM_PROCESSES control how many processes run inside the container
      # Normally this is set in connection with the number of CPU cores
      # Note however that you can also use the docker-compose scale option to dynamically
      # scale your thumbor instances
      - THUMBOR_NUM_PROCESSES=4
      # this would allow CORS from any origin (you can restrict to specific origins if you want)
      - CORS_ALLOW_ORIGIN=*
      # returns a webp image if browser Accept headers match
      - AUTO_WEBP=True
      # nginx-proxy does caching automatically, so no need to store the result storage cache
      # (this greatly speeds up and saves on CPU)
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      - STORAGE=thumbor.storages.file_storage
      - FILE_STORAGE_ROOT_PATH=/var/images
    restart: always
    networks:
      - app
    volumes:
      - ./images:/var/images
    ports:
      - "8888:80"
networks:
  app:
    driver: bridge
```

If it still doesn't work, can you try to create a reproducible `docker-compose.yml` file ?
